export default {
    'Web developer': 'Веб разработчик',
    'Mikhail Davlichin': 'Михаил Давличин',
    'lets coding!': 'Раз два и впродакшн',
    'City': 'Город',
    'Specialization': 'Специальность',
    'Education': 'Образование',
    'Sochi': 'Сочи',
    'Bachelor\'s degree': 'Специалист',
    'Information Systems and Technologies': 'Информационные системы и технологии',
    'Development experience': 'Опыт разрабоки',
    'All IT experience': 'Опыт в ИТ',
    'You': 'Вы',
    'Sign in': 'Вход',
    'Sign in with Google': 'Войдите в аккаунт Google',
    'to continue to': 'переход в приложение',
    'Email or phone': 'Телефон или адрес эл. почты',
    'Forgot email': 'Забыли адрес эл. почты',
    'google_access': 'Продолжая, вы разрешаете Google предоставить приложению "paktusin.github.io" доступ к вашему имени, адресу электронной почты и фото профиля',
    'Next': 'Далее',
    'Help': 'Справка',
    'Privacy': 'Конфиденциальность',
    'Terms': 'Условия',
    'Developer info': 'Информация о разработчике',
    'Email': 'Эл. почта',
    'Signing in will redirect you to:': 'Если вы выполните вход, то вернетесь в',
    'Got it': 'Продолжить',
    'About me': 'Обо мне',
    'Projects': 'Проекты',
    'Skills': 'Навыки',
    'SignIn': 'Вход',
    'Certificates': 'Сертификаты',
    'skills': 'навыков',
    'Demo projects for training': 'Демо проекты для тренировки',
    'External projects': 'Проекты на заказ',
    'Show more comments': 'Показать следующие комментарии',
    'Write comment': 'Написать комментарий',
};